#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c '
        logger -t bandix "[Bandix-Page] running..."
        while true; do
            /usr/bin/bandix-flush || logger -t bandix "flush failed"
            /usr/bin/bandix-quota
            sleep 120
        done
    '
    procd_set_param respawn
    procd_close_instance
}
